baseURL = "http://example.org/"
languageCode = "en-us"
summarylength = 25
title = "spoednik | Uw instroom van gevalideerde leads"
[[menu.nav]]
name = "Home"
url = ""
weight = 1
[[menu.nav]]
name = "About"
url = "about"
weight = 2
[[menu.nav]]
name = "Portfolio"
url = "portfolio"
weight = 3
[[menu.nav]]
name = "Blog"
url = "blog"
weight = 4
[[menu.nav]]
name = "Get in touch"
url = "contact"
weight = 5
[params]
author = "StaticMania"
dateFormat = "26 FEB 1994"
description = "Roxo Hugo themes | Design Agency Template by StaticMania"
formspreeFormUrl = "https://formspree.io/myykjpje"
googleAnalitycsID = "Your ID"
logo = "images/logo.png"
[params.banner]
background_image = "images/backgrounds/hero-background.jpg"
enable = true
heading = "We’re a Design Studio That Belies In the Great Ideas"
primary_button = "See Our Works"
primary_button_url = "portfolio"
secondary_button = "Connect with Us"
secondary_button_url = "contact"
tagline = "WE WORK HARD, WE PLAY HARD"
[params.call_to_action]
background_image = "images/backgrounds/cta-background.jpg"
enable = true
primary_button = "Submit Query"
primary_button_url = "contact"
secondary_button = "Not Convinced"
secondary_button_url = "portfolio"
title = "LET’S WORK TOGETHER"
[params.footer.contactInfo]
address = "713 Elmwood St.<br>Prior Lake, MN 55372"
email = "info@roxo.co"
phone = "409-896-1444"
title = "Contact Info"
[params.footer.service]
description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
title = "We help brands:"
[params.footer.sitemap]
title = "Sitemap"
[[params.footer.sitemap.link]]
name = "About Company"
url = "about"
[[params.footer.sitemap.link]]
name = "Projects"
url = "portfolio"
[[params.footer.sitemap.link]]
name = "Blog"
url = "blog"
[[params.footer.sitemap.link]]
name = "Contact"
url = "contact"
[params.footer.social]
title = "Social Media"
[[params.footer.social.link]]
name = "Medium"
url = "#"
[[params.footer.social.link]]
name = "Behance"
url = "#"
[[params.footer.social.link]]
name = "Dribbble"
url = "#"
[[params.footer.social.link]]
name = "Instagram"
url = "#"
[params.navAction]
name = "Get in touch"
status = true
url = "contact"
[params.portfolio]
enable = true
subtitle = "Crafting experiences and seeking to make the complex clear & beautiful."
title = "OUR RECENT WORK"
